import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shahed Abid Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Toaster
          toastOptions={{
            className: "",
            style: {
              border: "1px solid #87ceeb",
              padding: "16px",
              color: "black",
            },
          }}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
